movies = [{'Name':'Matrix','Year':'1999','Genre':'Action','Director':'Andy Wachowski and Lana Wachowski','Stars':'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss','Rating':'8.7/10'},
{'Name':'Raiders of the Lost Ark','Year':'1981','Genre':'Action','Director':'Steven Spielberg','Stars':'Harrison Ford, Karen Allen, Paul Freeman','Rating':'8.5/10'},
{'Name':'Deadpool','Year':'2016','Genre':'Action','Director':'Tim Miller','Stars':'Ryan Reynolds, Morena Baccarin, T.J. Miller','Rating':'8.5/10'},
{'Name':'Heat','Year':'1995','Genre':'Action','Director':'Michael Mann','Stars':'Al Pacino, Robert De Niro, Val Kilmer','Rating':'8.2/10'},
{'Name':'Die Hard','Year':'1988','Genre':'Action','Director':'John McTiernan','Stars':'Bruce Willis, Alan Rickman, Bonnie Bedelia','Rating':'8.2/10'},
{'Name':'300','Year':'2006','Genre':'Action','Director':'Zack Snyder','Stars':'Gerard Butler, Lena Headey, David Wenham','Rating':'7.7/10'},
{'Name':'Back to the Future','Year':'1985','Genre':'Comedy','Director':'Robert Zemeckis','Stars':' Michael J. Fox, Christopher Lloyd, Lea Thompson','Rating':'8.5/10'},
{'Name':'Coming to America','Year':'1988','Genre':'Comedy','Director':'John Landis','Stars':'Eddie Murphy, Arsenio Hall, James Earl Jones','Rating':'6.9/10'},
{'Name':'The Big Lebowski','Year':'1998','Genre':'Comedy','Director':'Joel Coen and Ethan Coen','Stars':'Jeff Bridges, John Goodman, Julianne Moore','Rating':'8.2/10'},
{'Name':'The Interview','Year':'2014','Genre':'Comedy','Director':'Evan Goldberg and Seth Rogen','Stars':'James Franco, Seth Rogen, Randall Park','Rating':'6.6/10'},
{'Name':'Clueless','Year':'1995','Genre':'Comedy','Director':'Amy Heckerling','Stars':'Alicia Silverstone, Stacey Dash, Brittany Murphy','Rating':'6.8/10'},
{'Name':'Into the Wild','Year':'2007','Genre':'Drama','Director':'Sean Penn','Stars':'Emile Hirsch, Vince Vaughn, Catherine Keener','Rating':'8.2/10'},
{'Name':'Gran Torino','Year':'2008','Genre':'Drama','Director':'Clint Eastwood','Stars':'Clint Eastwood, Bee Vang, Christopher Carley','Rating':'8.2/10'},
{'Name':'Pulp Fiction','Year':'1994','Genre':'Drama','Director':'Quentin Tarantino','Stars':'John Travolta, Uma Thurman, Samuel L. Jackson','Rating':'8.9/10'},
{'Name':'Léon','Year':'1994','Genre':'Drama','Director':'Luc Besson','Stars':'Jean Reno, Gary Oldman, Natalie Portman','Rating':'8.6/10'},
{'Name':'The Lord of the Rings: The Fellowship of the Ring','Year':'2001','Genre':'Fantasy','Director':'Peter Jackson','Stars':'Elijah Wood, Ian McKellen, Orlando Bloom','Rating':'8.8/10'},
{'Name':'It\'s a Wonderful Life','Year':'1946','Genre':'Fantasy','Director':'Frank Capra','Stars':'James Stewart, Donna Reed, Lionel Barrymore','Rating':'8.6/10'},
{'Name':'Life of Pi','Year':'2012','Genre':'Fantasy','Director':'Ang Lee','Stars':'Suraj Sharma, Irrfan Khan, Adil Hussain','Rating':'8.0/10'},
{'Name':'Harry Potter and the Sorcerer\'s Stone','Year':'2001','Genre':'Fantasy','Director':'Chris Columbus','Stars':'Daniel Radcliffe, Rupert Grint, Richard Harris, Emma Watson','Rating':'7.5/10'},
{'Name':'Mary Poppins','Year':'1964','Genre':'Fantasy','Director':'Robert Stevenson','Stars':'Julie Andrews, Dick Van Dyke, David Tomlinson','Rating':'7.8/10'},
{'Name':'Eternal Sunshine of the Spotless Mind','Year':'2004','Genre':'Romance','Director':'Michel Gondry','Stars':'Jim Carrey, Kate Winslet, Tom Wilkinson','Rating':'8.4/10'},
{'Name':'Before Sunrise','Year':'1995','Genre':'Romance','Director':'Richard Linklater','Stars':'Ethan Hawke, Julie Delpy, Andrea Eckert','Rating':'8.1/10'},
{'Name':'The Perks of Being a Wallflower','Year':'2012','Genre':'Romance','Director':'Stephen Chbosky','Stars':'Logan Lerman, Emma Watson, Ezra Miller','Rating':'8.0/10'},
{'Name':'The Vow','Year':'2012','Genre':'Romance','Director':'Michael Sucsy','Stars':'Rachel McAdams, Channing Tatum, Sam Neill','Rating':'6.8/10'},
{'Name':'Psycho','Year':'1960','Genre':'Thriller','Director':'Alfred Hitchcock','Stars':'Anthony Perkins, Janet Leigh, Vera Miles','Rating':'8.5/10'},
{'Name':'Shutter Island','Year':'2010','Genre':'Thriller','Director':'Martin Scorsese','Stars':'Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo','Rating':'8.1/10'},
{'Name':'The Silence of the Lambs','Year':'1991','Genre':'Thriller','Director':'Jonathan Demme','Stars':'Jodie Foster, Anthony Hopkins, Lawrence A. Bonney','Rating':'8.6/10'},
{'Name':'Mystic River','Year':'2003','Genre':'Thriller','Director':'Clint Eastwood','Stars':'Sean Penn, Tim Robbins, Kevin Bacon','Rating':'8.0/10'},
{'Name':'Spectre','Year':'2015','Genre':'Thriller','Director':'Sam Mendes','Stars':'Daniel Craig, Christoph Waltz, Léa Seydoux','Rating':'6.9/10'}]

for item in movies:
	print item
